### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by koehn** [bitnami/bitnami-docker-wal-g#1]
Given that `wal-g` needs to be run by the postgres server in order to know when WAL files need to be transported (for backup or recovery), and this image isn't integrated with Postgres, how exactly do you use this image?

**Comment by andresbono** [comment]
Hi @koehn, for the specific usage of the tool with PostgreSQL I'd recommend you to take a look at the upstream guide: https://github.com/wal-g/wal-g/blob/master/PostgreSQL.md#configuration

**Comment by koehn** [comment]
Thanks, but I know how to use WAL-G, which was why my question was about how to use this image. 

Per the WAL-G instructions, you are to configure `postgres.conf` to run `wal-g backup-push` in order to send a WAL file to S3 storage. But since this image isn’t a Postgres image, and the `wal-g` binary isn’t accessible to the Postgres process (which would have to be running in another container), I don’t understand how this image is to be used. 

Is there any kind of usage guide that demonstrates how it is to be integrated with a running Postgres instance inside another container?

**Comment by andresbono** [comment]
> Is there any kind of usage guide that demonstrates how it is to be integrated with a running Postgres instance inside another container?

I'm afraid that we don't have that piece of documentation.

As an example, and for testing purposes, we tried with the following docker-compose:

```yaml
version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:12-debian-10
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
  wal-g:
    image: docker.io/bitnami/wal-g:0-debian-10
    user: root
    command: --walg-file-prefix=/tmp/backups --pghost=postgresql --pguser=postgres backup-push /bitnami/postgresql/data/
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
      - './backups:/tmp/backups'
    depends_on:
      - postgresql
    restart: on-failure

volumes:
  postgresql_data:
    driver: local
```

By sharing the postgresql data volume between both containers, we could create a backup successfully. For simplicity, it's using `walg-file-prefix` to store the backup in the filesystem instead of configuring a S3 bucket or other storage service.

These are the logs:

```console
$ docker-compose logs wal-g
wal-g_1       | INFO: 2020/12/01 08:51:17.581881 Doing full backup.
wal-g_1       | WARNING: 2020/12/01 08:51:17.596869 It seems your archive_mode is not enabled. This will cause inconsistent backup. Please consider configuring WAL archiving.
wal-g_1       | INFO: 2020/12/01 08:51:17.597835 Calling pg_start_backup()
wal-g_1       | INFO: 2020/12/01 08:51:17.664198 Walking ...
wal-g_1       | INFO: 2020/12/01 08:51:17.664419 Starting part 1 ...
wal-g_1       | INFO: 2020/12/01 08:51:17.946356 Finished writing part 1.
wal-g_1       | INFO: 2020/12/01 08:51:17.946381 Starting part 2 ...
wal-g_1       | INFO: 2020/12/01 08:51:17.946436 /global/pg_control
wal-g_1       | INFO: 2020/12/01 08:51:17.949764 Finished writing part 2.
wal-g_1       | INFO: 2020/12/01 08:51:17.950544 Calling pg_stop_backup()
wal-g_1       | INFO: 2020/12/01 08:51:17.976066 Starting part 3 ...
wal-g_1       | INFO: 2020/12/01 08:51:17.978446 backup_label
wal-g_1       | INFO: 2020/12/01 08:51:17.978566 tablespace_map
wal-g_1       | INFO: 2020/12/01 08:51:17.978672 Finished writing part 3.
wal-g_1       | INFO: 2020/12/01 08:51:17.981214 Wrote backup with name base_000000010000000000000002
```

I hope you find this useful.
