### ISSUE TITLE
remote backup-push command error with unknown userid

### ISSUE THREAD

**Issue by thangamani-arun** [bitnami/bitnami-docker-wal-g#5]
**Description**

When I run `wal-g:1.1.0-debian-10-r171` as a pod in kubernetes and try to invoke a remote backup-push command, it throws unknown userid error. The wal-g pod and postgresql cluster pods are running in the same namespace of k8s. The idea here is to push the backup from postgresql-cluster using `wal-g` pod and push the wal logs to S3 to restore it to a remote standby cluster. 

**Steps to reproduce the issue:**

1. Create a pod on a kubernetes as follows. Create `wal-g.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wal-g
  namespace: postgres-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wal-g
  template:
    metadata:
      labels:
        app: wal-g
    spec:
      containers:
        - name: wal-g
          image: bitnami/wal-g:1.1.0-debian-10-r171
          imagePullPolicy: "IfNotPresent"
          command: ["/bin/sleep", "3650d"]
```
`kuberctl apply -f wal-g.yaml`
2. ```kubectl exec -n postgres-cluster -it <pod-name> -- /bin/bash```

**Describe the results you received:**

Actual command used for wal backup-push
```
wal-g backup-push     --aws-access-key=s3-access-key     --aws-secret-access-key=ANNNNNNNNNNNNNNN    --aws-endpoint=https://xx.xxx.xxx.xxx     --walg-s3-prefix=s3://postgres-cluster-wal-backup/     --pgdata=/bitnami/postgresql/data     --pghost=xxx.xxx.xxx.xxx     --pguser=postgres    --pgpassword=postgres     --pgdatabase=postgres     --aws-s3-force-path-style=true
```

```
ERROR: 2022/02/07 03:52:12.752277 user: unknown userid 1001
```

above error pops-up even without any flags: 
```
I have no name!@wal-g-6d95bf6489-29t9m:/$ wal-g backup-push
ERROR: 2022/02/07 03:52:12.752277 user: unknown userid 1001
```

**Describe the results you expected:**

It suppose to ship the wal backups to S3
